repos:
- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.4.0
  hooks:
    - id: go-fmt
    - id: go-lint
    - id: go-imports
    - id: go-unit-tests
    - id: go-build
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.50.0
  hooks:
    - id: terraform_fmt
      stages: [commit]
    - id: terraform_tflint
      stages: [commit]
    - id: terraform_docs
      stages: [commit]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: end-of-file-fixer
      stages: [commit]
    - id: trailing-whitespace
      stages: [commit]
    - id: check-merge-conflict
      stages: [commit]
