-- SnowSQL create statements
GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE ${database} TO ROLE ${role};
GRANT ALL PRIVILEGES ON ALL VIEWS IN DATABASE ${database} TO ROLE ${role};
GRANT ALL PRIVILEGES ON ALL FILE FORMATS IN DATABASE ${database} TO ROLE ${role};
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN DATABASE ${database} TO ROLE ${role};
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN DATABASE ${database} TO ROLE ${role};
GRANT ALL PRIVILEGES ON ALL STREAMS IN DATABASE ${database} TO ROLE ${role};
GRANT ALL PRIVILEGES ON ALL PROCEDURES IN DATABASE ${database} TO ROLE ${role};
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE ${database} TO ROLE ${role};
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN DATABASE ${database} TO ROLE ${role};
GRANT ALL PRIVILEGES ON FUTURE FILE FORMATS IN DATABASE ${database} TO ROLE ${role};
GRANT ALL PRIVILEGES ON FUTURE SEQUENCES IN DATABASE ${database} TO ROLE ${role};
GRANT ALL PRIVILEGES ON FUTURE FUNCTIONS IN DATABASE ${database} TO ROLE ${role};
GRANT ALL PRIVILEGES ON FUTURE STREAMS IN DATABASE ${database} TO ROLE ${role};
GRANT ALL PRIVILEGES ON FUTURE PROCEDURES IN DATABASE ${database} TO ROLE ${role};
