-- SnowSQL delete statements
REVOKE ALL PRIVILEGES ON ALL TABLES IN DATABASE ${database} FROM ROLE ${role};
REVOKE ALL PRIVILEGES ON ALL VIEWS IN DATABASE ${database} FROM ROLE ${role};
REVOKE ALL PRIVILEGES ON ALL FILE FORMATS IN DATABASE ${database} FROM ROLE ${role};
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN DATABASE ${database} FROM ROLE ${role};
REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN DATABASE ${database} FROM ROLE ${role};
REVOKE ALL PRIVILEGES ON ALL STREAMS IN DATABASE ${database} FROM ROLE ${role};
REVOKE ALL PRIVILEGES ON ALL PROCEDURES IN DATABASE ${database} FROM ROLE ${role};
REVOKE ALL PRIVILEGES ON FUTURE TABLES IN DATABASE ${database} FROM ROLE ${role};
REVOKE ALL PRIVILEGES ON FUTURE VIEWS IN DATABASE ${database} FROM ROLE ${role};
REVOKE ALL PRIVILEGES ON FUTURE FILE FORMATS IN DATABASE ${database} FROM ROLE ${role};
REVOKE ALL PRIVILEGES ON FUTURE SEQUENCES IN DATABASE ${database} FROM ROLE ${role};
REVOKE ALL PRIVILEGES ON FUTURE FUNCTIONS IN DATABASE ${database} FROM ROLE ${role};
REVOKE ALL PRIVILEGES ON FUTURE STREAMS IN DATABASE ${database} FROM ROLE ${role};
REVOKE ALL PRIVILEGES ON FUTURE PROCEDURES IN DATABASE ${database} FROM ROLE ${role};
